### ISSUE TITLE
ストアドプロシージャ｛確認お願いします｝

### ISSUE THREAD

**Issue by ynanba2015** [ynanba2015/nanba#11]

**Comment by ynanba2015** [comment]
DELIMITER //
CREATE PROCEDURE PR1()
BEGIN
SELECT * FROM tb;
SELECT * FRML tb1;
END
//
DELIMITER ;

----------------------
CALL ストアドプロシージャ名;

**Comment by lassicaoki** [comment]
いいんじゃないでしょうか。

これって、いま作成中のplayflameworkのアプリに組み込めないかな？
