### ISSUE TITLE
SQL結合｛確認お願いします｝

### ISSUE THREAD

**Issue by lassicnanba** [ynanba2015/nanba#2]
SELECT mt_stage.stamt_stagemt_stagege_name
FROM dt_score_management
INNER JOIN mt_stage
ON dt_score_management.stage_id = mt_stage.stage_id
where member_id = 94

内部結合と外部結合の違い
内部結合
・2つの表を結合としたさい、対応する値が無いものは表示されない

外部結合
・2つの表を結合としたさい、対応する値が無いものも表示される
![join](https://cloud.githubusercontent.com/assets/13962536/10983339/5a9c8e96-8455-11e5-8637-04a7969fbc36.JPG)

**Comment by lassicaoki** [comment]
SELECT メンバID
FROM テーブル１
OUTER JOIN mt_stage
ON テーブル１.ID　＝　テーブル２.ID
where id = 3


return：エラー or ”” or NULL　のどれか？


---

* LEFT OUTER JOIN
* RIGHT OUTER JOIN
* FULL OUTER JOIN
  * これらの違いは？

**Comment by ynanba2015** [comment]
LEFT OUTER JOIN：FROMで指定されたテーブルのカラムが全て出る
RIGHT OUTER JOIN：JOINで指定されたテーブルのカラムが全て出る
FULL OUTER JOIN：両方のカラムが全て出る
