### ISSUE TITLE
xml｛確認お願いします｝

### ISSUE THREAD

**Issue by ynanba2015** [ynanba2015/nanba#4]
ツリー状のデータ
入れ子
値を書く

**Comment by ynanba2015** [comment]
// xml宣言　バージョン、文字コード、スタンドアロン文書
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

// 要素
<要素>コンテンツ</要素>

//属性　名前と値のセットで使われる
<要素 属性名="値">コンテンツ</要素>

xmlはデータを木構造で記述する
要素同士の親子関係がある
親要素：要素1
子要素：要素2、要素3

-------------------
<要素1>
	<要素2></要素2>
	<要素3></要素3>
</要素1>

-------------------

xml:space属性
→スペースを保存するかどうかの設定
default：デフォルト動作を示す
preserve:スペースを保存する

xml:lang属性
→コンテンツがどの言語で記述されているか示す属性

CDATAセクション
→全て文字として解釈される(タグも)
<![CDATA[コンテンツ]]>

DTD(Document Type Definition)
・xmlの形式の宣言

DOCTYPE宣言
<!DOCTYPE ルート属性 >

**Comment by lassicaoki** [comment]
最後

* あるシステムで、インポート機能を実装しました
  * 元になるファイルとして、CSVファイル、XMLファイルの２種類があります
  * それぞれ下記のような構成です

* CSV
```
"1000","田中","次郎","総務"
```

* XML
```
<社員情報>
  <社員番号>1000</社員番号>
  <氏名>
    <姓>田中</姓>
    <名>次郎</名>
  </氏名>
  <部署>総務</部署>
</社員情報>
```

* このとき、INPUTとしてXMLを選択するとどんなメリットがあるでしょうか
  * ヒント： http://www.atmarkit.co.jp/ait/articles/0110/05/news004.html

**Comment by ynanba2015** [comment]
・修正が容易になる
→タグで読み込ませるため。
→追加の項目が会った場合でも、追加タグを読み込むようにするだけですむから。
