### ISSUE TITLE
正規化｛確認お願いします｝

### ISSUE THREAD

**Issue by ynanba2015** [ynanba2015/nanba#5]
テーブルを管理しやすい形に変形する

第一正規化
・重複
第二正規化
・部分関数従属
第三正規化
・複合関数従属

**Comment by lassicaoki** [comment]
* 何も正規化してない
  * 非正規系

* 残
  * イメージしやすい例を挙げる
  * 人に説明できたらクリア

**Comment by ynanba2015** [comment]
社員番号　名前　ステージ　チームid　所属チーム

非正規形(一人の社員が複数のチームに所属している)
001　田中太郎　PG　1　Aチーム、2　Bチーム

第一正規形(一つのカラムに一人、一つのチーム)
社員番号　名前　ステージ　チームid　所属チーム
001　田中太郎　PG　1　Aチーム
001　田中太郎　PG　2　Bチーム


第二正規形(社員IDでわかる項目を分ける)
社員番号　名前　ステージ
001　田中太郎　PG

社員番号　チームid　所属チーム
001　1　Aチーム
001　2　Bチーム


第三正規形(チームIDがわかれば、チーム名がわかる)
社員番号　名前　ステージ
001　田中太郎　PG

社員番号　チームid
001　1
001　2

チームid　所属チーム
1　Aチーム
2　Bチーム
