### ISSUE TITLE
トランザクション｛確認お願いします｝

### ISSUE THREAD

**Issue by ynanba2015** [ynanba2015/nanba#6]
複数の処理を一つにまとめる
begin

　この間に処理を書く

commit

**Comment by lassicaoki** [comment]
* うまくいったらcommitコマンドでDBに反映される
* 途中でこけたときはどうなる？
  * beginで始める前の状態になる
  * ⇒たぶんなる
  * ⇒rollbackの書き方

**Comment by ynanba2015** [comment]
>途中でこけたときはどうなる？

→beginで始まる前の状態に戻す(この処理をロールバックという)

rollbackの書き方
→rollback　SQL文

**Comment by lassicaoki** [comment]
* 上記、調査はOKです。
* 下記のサンプルコードにコミットとロールバックの処理＋＠を追記してください。
  * 追記してほしいのは(★)の部分です
  * できれば他の項目についても下記のようなサンプルコードを記載してほしいです

```
   Connection con = null;
   Statement st = null;
 
   try {
       // JDBCドライバをロード
       Class.forName("oracle.jdbc.driver.OracleDriver");
       // DB接続オブジェクト
       con = DriverManager.getConnection("jdbc:oracle:thin:～", "scott", "tiger");
       // 自動コミット解除
       con.setAutoCommit(false);
       // ステートメントを作成
       st = con.createStatement();
 
       // 処理1
       st.executeUpdate("UPDATE TABLE_A ～");
       // 処理2
       st.executeUpdate("UPDATE TABLE_B ～");
 
       // コミット(★)
       
   }
   catch (Exception e) {
       /** ログ出力 */
       try {
           // ロールバック(★)
           
       }
       catch (SQLException se) {
          /** ログ出力 */
       }
   }
   finally {
       try {
           // ステートメントのクローズ(★)
           

           // DB接続のクローズ(★)
           
       }
       catch (SQLException se) {
          /** ログ出力 */
       }
   }
```

**Comment by lassicaoki** [comment]
↑ これ、アオキのコメントをUPDATEするんじゃなくて、ソースコードの部分をコピーして、コメント追記してください。

**Comment by lassicnanba** [comment]
Connection con = null;
   Statement st = null;

   try {
       // JDBCドライバをロード
       Class.forName("oracle.jdbc.driver.OracleDriver");
       // DB接続オブジェクト
       con = DriverManager.getConnection("jdbc:oracle:thin:～", "scott", "tiger");
       // 自動コミット解除
       con.setAutoCommit(false);
       // ステートメントを作成
       st = con.createStatement();

       // 処理1
       st.executeUpdate("UPDATE TABLE_A ～");
       // 処理2
       st.executeUpdate("UPDATE TABLE_B ～");

       // コミット(★)
       commit;
   }
   catch (Exception e) {
       /** ログ出力 */
       try {
           // ロールバック(★)
           rollback;
       }
       catch (SQLException se) {
          /** ログ出力 */
       }
   }
   finally {
       try {
           // ステートメントのクローズ(★)


           // DB接続のクローズ(★)

       }
       catch (SQLException se) {
          /** ログ出力 */
       }
   }

**Comment by lassicaoki** [comment]
https://github.com/ynanba2015/nanba/issues/6#issuecomment-156360196
エラーが出ないように正確に記載をお願いします。
（たぶん上記だとコンパイルとおらないはず）

**Comment by ynanba2015** [comment]
```Java
   Connection con = null;
   Statement st = null;

   try {
       // JDBCドライバをロード
       Class.forName("oracle.jdbc.driver.OracleDriver");
       // DB接続オブジェクト
       con = DriverManager.getConnection("jdbc:oracle:thin:～", "scott", "tiger");
       // 自動コミット解除
       con.setAutoCommit(false);
       // ステートメントを作成
       st = con.createStatement();

       // 処理1
       st.executeUpdate("UPDATE TABLE_A ～");
       // 処理2
       st.executeUpdate("UPDATE TABLE_B ～");

       // コミット(★)
       con.commit;
   }
   catch (Exception e) {
       /** ログ出力 */
       try {
           // ロールバック(★)
           con.rollback;
       }
       catch (SQLException se) {
          /** ログ出力 */
       }
   }
   finally {
       try {
           // ステートメントのクローズ(★)
　　　  st.close();

           // DB接続のクローズ(★)
           con.close();
       }
       catch (SQLException se) {
          /** ログ出力 */
       }
   }
```

**Comment by lassicaoki** [comment]
大丈夫かと思います。

同様ですが、覚えておいてください
https://github.com/ynanba2015/nanba/issues/12#issuecomment-157939197
