### ISSUE TITLE
制約｛確認お願いします｝

### ISSUE THREAD

**Issue by ynanba2015** [ynanba2015/nanba#7]
DBに登録するデータの型指定
NULLを設定できるかどうか

**Comment by lassicaoki** [comment]
* 指定するタイミング
  * テーブル作成時
  * →残：MySQLでテーブル作成時に制約を指定する

**Comment by ynanba2015** [comment]
create table テーブル名(項目名 データ型 制約);

以下、例nullの設定

create table テーブル名(項目1 データ型 null,項目2 データ型 not null,項目3 データ型);
項目1：nullを許可しない(nullがあるとエラーになる)
項目2：nullを許可する
項目3：nullを許可する

**Comment by lassicaoki** [comment]
> create table テーブル名(項目1 データ型 null,項目2 データ型 not null,項目3 データ型);
> 項目1：nullを許可しない(nullがあるとエラーになる)
> 項目2：nullを許可する

え、逆ではなくて？
（勘違いだったらごめん）

**Comment by lassicnanba** [comment]
あ、逆でした。
項目1：nullを許可する
項目2：nullを許可しない(nullがあるとエラーになる)
