### ISSUE TITLE
インターフェース｛確認お願いします｝

### ISSUE THREAD

**Issue by lassicnanba** [ynanba2015/nanba#8]
■インターフェースの書き方
[修飾子] interface <インタフェース名> {
	データ型 変数名 = 値;
	修飾子 戻り値のデータ型 メソッド名(引数の型宣言);
}

■実装
implements <インタフェース名>{
}

**Comment by lassicaoki** [comment]
* メリットがいまいちピンときてない
  * 要調査

**Comment by ynanba2015** [comment]
インターフェース
・継承ではなく、実装という
・1つのクラスが複数のインターフェースを実装することができる
・メソッドの中身が無いため、中身を書く必要がある
・プログラムを書く際に、最初の方で書くため間違えないように注意が必要
　・最初のうちに書いて後で、使用するため仕様を守らせることができる(同じ名前のメソッドを使うため)

**Comment by lassicaoki** [comment]
この辺見たらメリットとか書いてあるかも
* https://github.com/ynanba2015/nanba/wiki/JC%E3%83%A1%E3%83%A2#%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%95%E3%82%A7%E3%83%BC%E3%82%B9

**Comment by ynanba2015** [comment]
・接続するクラスを選べる

**Comment by lassicnanba** [comment]
・開発が楽になる
⇒各クラスに共通するメソッドのをインターフェースにすることで、名前が共通化される
　⇒インターフェースが実装されていれば、そのメソッドが使える
